/**
 * Rendering the tokens as CSS variables, for the demo's DOM shell.
 *
 * This module deliberately sits OUTSIDE the index: the index stays pure data,
 * consumable by the Pixi renderer, which has no use for a CSS string. It is
 * exposed through the package's `"./css"` export.
 *
 * The output reproduces, byte for byte, the `:root` and
 * `html[data-theme="dark"]` blocks that `apps/demo/src/style.css` used to carry
 * inline: wiring the tokens in must change nothing in how the demo renders. Any
 * difference in value, order or formatting would show — which is precisely what
 * the generated file's freshness test watches.
 */

import {
  type ChromeTokens,
  type ColorTokens,
  chrome,
  cssFontStack,
  defsquare,
  motion,
  radii,
  spacing,
} from "./index.js";

/** A declaration in the legacy format: two spaces of indentation. */
function decl(name: string, value: string): string {
  return `  --${name}: ${value};`;
}

/**
 * A theme's colors. `--ds-accent` is optional because the legacy stylesheet
 * only declares it in `:root`: the selection value is identical in both themes,
 * so the dark block has nothing to add.
 */
function colorDecls(colors: ColorTokens, ui: ChromeTokens, withAccent: boolean): string[] {
  return [
    decl("ds-canvas", colors.surface.canvas),
    decl("ds-surface", colors.surface.card),
    decl("ds-surface-muted", colors.surface.cardMuted),
    decl("ds-ink", colors.ink.primary),
    // `--ds-fg` comes from the chrome, not from the ink: the shell's text is
    // more contrasted than that of the canvas cards.
    decl("ds-fg", ui.fg),
    decl("ds-link", ui.link),
    decl("ds-muted", colors.ink.muted),
    decl("ds-subtle", colors.ink.subtle),
    ...(withAccent ? [decl("ds-accent", colors.accent.selection)] : []),
    decl("ds-primary", colors.accent.entity),
    decl("ds-border", colors.edge.border),
    decl("ds-border-soft", colors.edge.hairline),
  ];
}

/** Intent comment carried over from the legacy stylesheet. */
const FLOAT_INTENT = `  /* Floating surfaces: translucent so the graph shows through, but opaque
     enough to stay legible above a dense card. */`;

function floatDecls(ui: ChromeTokens): string[] {
  return [
    decl("float-bg", ui.float.bg),
    decl("float-border", ui.float.border),
    decl("float-hover", ui.float.hover),
    decl("shadow-float", ui.shadow),
  ];
}

/** Numeric scale in px: `radii` and `spacing` are expressed as bare pixels. */
function scaleDecls(prefix: string, scale: Record<string, number>): string[] {
  return Object.entries(scale).map(([key, value]) => decl(`${prefix}-${key}`, `${value}px`));
}

function fontDecls(fonts: typeof defsquare.fonts): string[] {
  return [
    ...(fonts.title ? [decl("font-title", cssFontStack(fonts.title))] : []),
    decl("font-body", cssFontStack(fonts.body)),
    decl("font-mono", cssFontStack(fonts.mono)),
  ];
}

/** Groups are separated by a blank line, as in the original stylesheet. */
function block(selector: string, groups: string[][]): string {
  return `${selector} {\n${groups.map((g) => g.join("\n")).join("\n\n")}\n}`;
}

const HEADER = `/* GENERATED by @defsquare/datagraph-tokens — DO NOT EDIT BY HAND.
   Regenerate: pnpm --filter @defsquare/datagraph-tokens generate:css
   A freshness test (packages/tokens/test/css.test.ts) breaks if this file
   drifts from the token source. */`;

/** The shell's complete CSS variable sheet, "generated" header included. */
export function renderTokensCss(): string {
  // `radii.card` is the radius of the cards Pixi draws: the DOM does not use
  // it, and exposing it here would invent a variable the legacy stylesheet
  // never had.
  const { card: _card, ...domRadii } = radii;

  const root = block(":root", [
    colorDecls(defsquare.light, chrome.light, true),
    [FLOAT_INTENT, ...floatDecls(chrome.light)],
    scaleDecls("radius", domRadii),
    scaleDecls("space", spacing),
    [decl("transition", motion.transition), decl("ease-out", motion.easeOut)],
    fontDecls(defsquare.fonts),
  ]);

  // The dark theme only overrides what changes: scales, motion and fonts are
  // inherited from `:root`.
  const dark = block('html[data-theme="dark"]', [
    colorDecls(defsquare.dark, chrome.dark, false),
    floatDecls(chrome.dark),
  ]);

  return `${[HEADER, root, dark].join("\n\n")}\n`;
}
