import {
  defsquareDark,
  defsquareLight,
  neutralDark,
  neutralLight,
  type Theme,
} from "@renderer/theme.ts";

/**
 * The playground's theme state, and the only place that mutates it.
 *
 * Two independent axes — the BRAND (which color set) and the MODE (light or
 * dark) — because that is how the renderer exposes its four themes. Crossing
 * them into a single four-valued enum would force every control in the UI to
 * know the other three combinations in order to know which one to switch to.
 *
 * A single module carries this state: the views (tokens, components, sandbox)
 * subscribe, they do not pass it around between themselves. A view receiving
 * the theme through a roundabout path would fall out of sync the day someone
 * adds a keyboard shortcut or URL restoration.
 */
export interface ThemeState {
  brand: "defsquare" | "neutral";
  mode: "light" | "dark";
}

// A table rather than four `if`s: the only knowledge this module has of the
// renderer's themes is that crossing, and it reads at a glance.
const THEMES: Record<ThemeState["brand"], Record<ThemeState["mode"], Theme>> = {
  defsquare: { light: defsquareLight, dark: defsquareDark },
  neutral: { light: neutralLight, dark: neutralDark },
};

let state: ThemeState = { brand: "defsquare", mode: "light" };

const subscribers = new Set<(s: ThemeState) => void>();

/** Snapshot of the current state. A copy: a caller mutating the internal object
 * would bypass `setTheme` and nobody would be notified. */
export function themeState(): ThemeState {
  return { ...state };
}

/** The Pixi theme matching a state. Pure: views that build a canvas call it
 * again on every remount rather than memorizing a reference. */
export function currentTheme(s: ThemeState): Theme {
  return THEMES[s.brand][s.mode];
}

/** Subscribes to changes. Returns the unsubscribe — views call it in their
 * cleanup, without which an unmounted view would keep reacting and would hold
 * its destroyed canvas alive. */
export function onThemeChange(cb: (s: ThemeState) => void): () => void {
  subscribers.add(cb);
  return () => {
    subscribers.delete(cb);
  };
}

/**
 * Changes one or both axes, then notifies.
 *
 * Early return if nothing changes: setting the same theme again would trigger a
 * full remount of the views (hence recreating the Pixi canvases) for nothing.
 */
export function setTheme(patch: Partial<ThemeState>): void {
  const next: ThemeState = { ...state, ...patch };
  if (next.brand === state.brand && next.mode === state.mode) return;
  state = next;
  applyMode();
  // Iterating over a copy: a subscriber may unsubscribe from within its own
  // callback — exactly what a view unmounting in reaction does.
  for (const cb of [...subscribers]) cb(themeState());
}

/**
 * The mode reaches CSS through `data-theme` on `<html>` — same mechanism as
 * `apps/demo/src/chrome.ts`, and it is the selector on which the sheet
 * generated by the token package (`html[data-theme="dark"]`) overrides its
 * colors. The brand, on the other hand, only changes the Pixi themes: today the
 * generated CSS variables cover the defsquare palette alone.
 */
function applyMode(): void {
  document.documentElement.setAttribute("data-theme", state.mode);
}

// The attribute is already set in `index.html`, but leaving it there alone would
// make the initial state a truth held in two copies. We restate it from the
// state.
applyMode();
